### ISSUE TITLE
Build fails on MacOS

### ISSUE THREAD

**Issue by m4dh4t** [stef/liboprf#1]
Hi. I was looking forward to build this lib as it is a dependency for [libopaque](https://github.com/stef/libopaque) and encountered the following error when running `make`:

```console
ld: unknown options: -z -z -z -z -soname 
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [liboprf.so] Error 1
```

Would you have any idea on how to handle this issue ?

Thanks for your help !

**Comment by stef** [comment]
i also pushed a similar fix to the makefile of libopaque...

**Comment by m4dh4t** [comment]
As the `make install` commands are also broken for MacOS, Python is not able to find the lib when doing `import opaque` and returns `ValueError: Unable to find libopaque`.

Tried to manually give it the compiled `.dylib` by running `DYLD_LIBRARY_PATH=libopaque/src  python3 app.py` but the returned error is more than I can chew...

```text
Traceback (most recent call last):
  File "./app.py", line 5, in <module>
    from opaque import (CreateRegistrationResponse,
  File "./venv/lib/python3.11/site-packages/opaque/__init__.py", line 26, in <module>
    opaquelib = ctypes.cdll.LoadLibrary(ctypes.util.find_library('opaque') or ctypes.util.find_library('libopaque'))
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/ctypes/__init__.py", line 454, in LoadLibrary
    return self._dlltype(name)
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/ctypes/__init__.py", line 376, in __init__
    self._handle = _dlopen(self._name, mode)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: dlopen(libopaque/src/libopaque.dylib, 0x0006): Symbol not found: _expand_message_xmd
  Referenced from: <068B6BAB-567F-34CE-848C-B890666161C4> ./libopaque/src/libopaque.dylib
  Expected in:     <068B6BAB-567F-34CE-848C-B890666161C4> ./libopaque/src/libopaque.dylib
```

I guess I will fallback to a VM to save myself an headache

**Comment by stef** [comment]
it is looking for liboprf

**Comment by stef** [comment]
dunno macs, do you need to do a ldconfig or something similar? do you even have liboprf somewhere in your ld_library_path?

**Comment by stef** [comment]
did you try `make install`?

**Comment by m4dh4t** [comment]
I did, here is the output:

```text
> make install
install -D liboprf.dylib /lib/liboprf.dylib.0
install: illegal option -- D
usage: install [-bCcpSsv] [-B suffix] [-f flags] [-g group] [-m mode]
               [-o owner] file1 file2
       install [-bCcpSsv] [-B suffix] [-f flags] [-g group] [-m mode]
               [-o owner] file1 ... fileN directory
       install -d [-v] [-g group] [-m mode] [-o owner] directory ...
make: *** [/lib/liboprf.dylib] Error 64
```

**Comment by stef** [comment]
hrmpf. thx. will try to push a fix for that, but i only in a few hours...

**Comment by m4dh4t** [comment]
Just retested using `ginstall` from GNU coreutils instead of install but as Mac's `/lib` is read-only the path would have to be changed to something else, tried with `/usr/local/lib` which copies it correctly, but it looks like `ctypes.util.find_library` is not able to fetch it

```makefile
ifeq ($(UNAME),Darwin)
	SOEXT=dylib
	SOFLAGS=-Wl,-install_name,liboprf.$(SOEXT)
	INSTALL=ginstall 
	PREFIX=/usr/local
else
	CFLAGS+=-Wl,-z,defs -Wl,-z,relro -Wl,-z,noexecstack -Wl,-z,now
	SOEXT=so
	SOFLAGS=-Wl,-soname,liboprf.$(SOEXT).$(SOVER)
endif
```

```console
$ make install
ginstall  -D liboprf.dylib /usr/local/lib/liboprf.dylib.0
ln -sf /usr/local/lib/liboprf.dylib.0 /usr/local/lib/liboprf.dylib
ginstall  -D liboprf.a /usr/local/lib/liboprf.a
ginstall  -D oprf.h /usr/local/include/oprf/oprf.h
ginstall  -D toprf.h /usr/local/include/oprf/toprf.h
ginstall  -D dkg.h /usr/local/include/oprf/dkg.h
```

```text
DYLD_LIBRARY_PATH=libopaque/src python3 app.py
Traceback (most recent call last):
  File "./app.py", line 5, in <module>
    from opaque import (CreateRegistrationResponse,
  File "./venv/lib/python3.11/site-packages/opaque/__init__.py", line 26, in <module>
    opaquelib = ctypes.cdll.LoadLibrary(ctypes.util.find_library('opaque') or ctypes.util.find_library('libopaque'))
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/ctypes/__init__.py", line 454, in LoadLibrary
    return self._dlltype(name)
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/ctypes/__init__.py", line 376, in __init__
    self._handle = _dlopen(self._name, mode)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: dlopen(libopaque/src/libopaque.dylib, 0x0006): Symbol not found: _expand_message_xmd
  Referenced from: <068B6BAB-567F-34CE-848C-B890666161C4> ./libopaque/src/libopaque.dylib
  Expected in:     <068B6BAB-567F-34CE-848C-B890666161C4> ./libopaque/src/libopaque.dylib
```

**Comment by stef** [comment]
two things: 

```sh
sudo PREFIX=/usr make install
```

you can just provide PREFIX in the commandline, no need to specify it in the makefile, so you can point it anywhere you want, and also yes, for certain paths like /usr you actually need root.

**Comment by stef** [comment]
> > libopaque.dylib, 0x0006): Symbol not found: _expand_message_xmd
> 
> Same issue here on MacOS.
> 
> I would love to use OPAQUE instead of SRP but I'm getting discouraged by how difficult it is to install the only up-to-date python bindings on MacOS.

1. do you have liboprf installed?
2. where do you have liboprf and libopaque installed?
3. if they are not on a global path, have you tried https://github.com/stef/liboprf/issues/1#issuecomment-2224115263

**Comment by stef** [comment]
as far as i looked it up, a simple `sudo make install` should install liboprf into a path where it will be found by python. this applies to both liboprf and libopaque (i just pushed changes to both projects makefiles that should make this more robust on macos and other systems lacking `-D` in `install(1)`)

otherwise i guess the best way forward is to find someone who packages stuff for brew and have liboprf/libopaque packaged for brew

**Comment by stef** [comment]
huh latest liboprf doesn't pass ci/cd pipeline for libopaque, will investigate.

**Comment by stef** [comment]
libopaque ci/cd pipline works again.

**Comment by stef** [comment]
so i changed `install -D` into `mkdir -p / cp ` everywhere, i set the one missing prefix for liboprf-noiseXK  to /usr/local, and disabled `-fcf-protection=full` in libopaque for Darwin. tell me if that fixes everything.

now the question is, why does darwin not find the libs that are installed into /usr/local via python? does `strace(1)` exist on darwin? would you run a strace on python trying to import opaque? and share the log via a pastebin?

**Comment by stef** [comment]
> <img alt="Screenshot 2024-07-12 at 19 39 44" width="1150" src="https://private-user-images.githubusercontent.com/31708119/348351552-7b05ddcc-791e-422d-baf3-c3db8b6e9cef.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA4MDk5MDcsIm5iZiI6MTcyMDgwOTYwNywicGF0aCI6Ii8zMTcwODExOS8zNDgzNTE1NTItN2IwNWRkY2MtNzkxZS00MjJkLWJhZjMtYzNkYjhiNmU5Y2VmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzEyVDE4NDAwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNkMDZjMjYwMjE3ODNmODZlY2JiNzYxZTZmYzlkMjlmNGIxM2YwNmY4MWY1NzBjYmY3ZTk3ODI1OTA5OGFlOGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.pF0haodu8j12YahlVYVzxKj1oj9HqrwaJcbkTwewjB8">
> 
> Here's what happens when I try to make liboprf with the last commit. I successfully built a commit from december last year but not this one.

please use a pastebin instead of a screenshot, makes the whole thing easier to copy paste and reference.

anyway this seems to be a very different issue. thank you for showing this even though it's just a screenshot. but that means, liboprf head doesn't build on darwin as far as i see. i'll have a look how to fix this...

**Comment by stef** [comment]
> Here's a pastebin of `python -v -c "import opaque" > import_log.txt 2>&1`: https://pastebin.com/eMWqf6Su
> 
> It seems it can find the lib fine but that the libopaque dylib is missing the `_expand_message_xmd`. Which I imagine should come from libsodium

nah, expand_message_xmd comes from liboprf. so you definitely need to have liboprf available. however the correct name is without a `_` prefix. so that's weird. do you have `nm(1)` available? would you do a `nm -D /usr/local/lib/liboprf.so` and a `nm -D /usr/local/lib/libopaque.so` if you do? also a `strace(1)` would be very useful.

also what happens if you do a simple "import pyoprf" while having liboprf and the python bindings installed? does that work?

**Comment by stef** [comment]
> Here's the pastebin for the liboprf `make > make_log.txt 2>&1` error. Although I think they are 2 unconnected errors but I can't guarantee that. https://pastebin.com/EgAHH7uD. That is on the last commit `884cf3f0a29eaaea2a51f1ac0d2202576a0d1ca5`

this is super cool, helps me fix those things. thanks!

**Comment by stef** [comment]
anyway, very much appreciated all this information, i really want to support macos, but i have zero access to it, so i am dependent on help like yours. thank you.

**Comment by stef** [comment]
> > nah, expand_message_xmd comes from liboprf. so you definitely need to have liboprf available. however the correct name is without a `_` prefix. so that's weird. do you have `nm(1)` available? would you do a `nm -D /usr/local/lib/liboprf.so` and a `nm -D /usr/local/lib/libopaque.so` if you do? also a `strace(1)` would be very useful.
> 
> `nm` output (no .so exists for me): https://pastebin.com/1Rxp310Y

aah. /o\ stupid me! sorry, not `.so` but `.dylib`

> ```
> strace: Linux is required for this software.
> linux-headers@5.15: Linux is required for this software.
> Error: strace: Unsatisfied requirements failed this build.
> ```

awwww. i can't imagine life without strace. the most useful debugging tool ever.

**Comment by stef** [comment]
> I confirm that importing pyoprf manually before opaque fixes the issue for me. Thanks a lot! Still there's the issue with making the last commit in oprf but that's not a problem for me for now.
> 
> ```python
> import pyoprf  # Without this opaque crashes on import. https://github.com/stef/liboprf/issues/1
> from opaque import CreateCredentialResponse, CreateRegistrationResponse, Ids, Register, StoreUserRecord, UserAuth
> ```

yeah, i expected this. what is weird is, that this doesnt work via dlopened libs finding (and loading their deps). as you can see python `dlopen()`s libopaque.dylib which in turn needs liboprf.dylib, but that somehow is not loaded (or found) and thus the missing symbol.

**Comment by stef** [comment]
i committed a bunch of fixes based on your fine input to liboprf. would you try to build it and install it?

**Comment by stef** [comment]
btw what happens if you do this?

```
python -c 'import ctypes, ctypes.util; ctypes.CDLL(ctypes.util.find_library("opaque"), mode=ctypes.RTLD_GLOBAL)'
```

and possibly also the output of

```
ldd /usr/local/lib/libopaque.dylib
```

much thankyous!

**Comment by stef** [comment]
huh, that make output looks super cool. the only thing that is missing is liboprf-noiseXK. how did you invoke `make`? in theory it should build liboprf-noiseXK before liboprf, but i guess it doesn't install it and then when it tries to link it, it won't work. let me try to fix that.

**Comment by stef** [comment]
> > btw what happens if you do this?
> > ```
> > python -c 'import ctypes, ctypes.util; ctypes.CDLL(ctypes.util.find_library("opaque"), mode=ctypes.RTLD_GLOBAL)'
> > ```
> 
> Same as before

hmmm, might be because your liboprf you do have installed doesn't have that symbol, but it'll be fixed when we manage to have it installed? i hope.

> ```
> otool -L /usr/local/lib/libopaque.dylib                                                                                                                         
> /usr/local/lib/libopaque.dylib:
> 	liboprf.dylib (compatibility version 0.0.0, current version 0.0.0)
```

interesting, there is no path here. while there is for libsodium. i'll fix this as well.

```
> 	/usr/local/lib/libsodium.26.dylib (compatibility version 29.0.0, current version 29.0.0)
```
```
> 	liboprf.dylib (compatibility version 0.0.0, current version 0.0.0)
```
why a second time? weird.

> EDIT: There's no ldd in MacOS, but I read that otool -L was the equivalent.
awesome

**Comment by stef** [comment]
i think i fixed both issues in the latest liboprf git revision. we now have an rpath for both libs (liboprf and liboprf-noiseXK) so if you do otool -L you should see a path to /usr/local/lib also for liboprf. i recommend to pull both repos to be up to date. run make first in liboprf/src: `sudo make install` and then in `libopaque/src` the same. then let's see if `otool -L` and `python -c 'import ctypes, ctypes.util; ctypes.CDLL(ctypes.util.find_library("opaque"), mode=ctypes.RTLD_GLOBAL)'` behave differently.

**Comment by stef** [comment]
fixed those. sloppy stupid mistake to have `liboprf-noiseXK.so` as a dep of `all` and not `liboprf-noiseXK.$(SOEXT)`

**Comment by stef** [comment]
i removed the rpath flags again. but i think the rest should have still improved. and might be working, i tried to search how to set rpath on macos, but it is all very confusing and conflicting info, maybe it all works without an rpath.

**Comment by stef** [comment]
> If you want, I would be happy to jump on some kind of instant messaging if you think it can help you fix this faster. If not I'm also happy to provide feedback here.

i don't really have any instant messaging besides IRC...

**Comment by stef** [comment]
so now you can do `import opaque` without first doing `import pyoprf` ?

fuck yeah! \o/

thank you very much for your patience and your help!

**Comment by stef** [comment]
i'm on ircnet on #libopaque as stf

**Comment by stef** [comment]
we did irc, and we did succeed.
